export const CREATE_PROGRAM = 'app/HomeCREATE_PROGRAM';
export const DESTROY_MEASUREMENT = 'app/Home/DESTROY_MEASUREMENT';
export const DESTROY_MEASUREMENT_SUCCESS = 'app/Home/DESTROY_MEASUREMENT_SUCCESS';
export const DESTROY_MEASUREMENT_FAIL = 'app/Home/DESTROY_MEASUREMENT_FAIL';
export const RECEIVE_CALORIES = 'app/Home/RECEIVE_CALORIES';
export const GET_CALORIES_MULTI = 'app/Home/GET_CALORIES_MULTI';
export const GET_CALORIES_MULTI_SUCCESS = 'app/Home/GET_CALORIES_MULTI_SUCCESS';
