export default [
  'Carrabbas Italian Grill',
  'Kentucky Fried Chicken',
  'Continental Mills, Inc',
  'Odwalla',
  'Dow AgroSciences, LLC',
  'Smart Soup',
  'General Mills Inc',
  'Barbaras Bakery, Inc',
  'George weston Bakeries, Inc',
  'Dominos Pizza, LLC',
  'Applebees',
  'Quaker Oats Company - The Gatorade Company,  a unit of Pepsi Co',
  'Taco Bell Corp',
  'Smart Balance Foods',
  'Chick-Fil-A',
  'The Dannon Company, Inc',
  'Crystal Geyser Alpine Spring Water',
  'Good Humor - Breyers Ice Cream',
  'Post Foods, LLC',
  'Nestle Waters North America Inc',
  'Pizza Hut, Inc',
  'Subway',
  'Campbell Soup Co',
  'Zevia',
  'Worthington Foods, Inc',
  'Kellogg, Co',
  'Hershey Food Corp',
  'Unilever',
  'WhiteWave Foods Company',
  'Homestat Farm Ltd',
  'Monster energy company',
  'The Weetabix Company',
  'H.J. Heinz, Co',
  'Abbotts Ross Products Division',
  'Little Caesars Pizza',
  'Vitasoy USA',
  'ConAgra, Inc',
  'Interstate Bakeries Corporation',
  'LUNA BAR',
  'CytoSport',
  'NAYA Inc',
  'Wm. Bolthouse Farms, Inc',
  'Hormel Foods Corp',
  'House Foods',
  'Masterfoods USA',
  'Nestle USA, Inc',
  'Kraft Foods, Inc',
  'Lipton',
  'Dole Food Company',
  'Cracker Barrel',
  'Icelandic Glacial Inc',
  'The Coca-Cola Company',
  'McDonalds Corporation',
  'Slim-Fast Foods Company',
  'Darden Group',
  'Sun Country Foods Inc',
  'S.A. Evian Co',
  'Burger King Corporation',
  'The J.M. Smucker Co',
  'Popeyes Chicken and Biscuits',
  'MOM Brands',
  'Nabisco Brands, Inc',
  'GFA Brands',
  'B&G Foods, Inc',
  'Anheuser-Busch, Inc',
  'Keebler, Co',
  'Ocean Spray Cranberries, INc',
  'Red Bull North America/Red Bull GmbH',
  'Pepsi-Cola North America',
  'Pillsbury Co',
  'ADM KAO LLC',
  'Natures Path',
  'T.G.I Fridays',
  'Naked Juice Co. of Glendora, Inc',
  'Ralston Foods',
  'Papa Johns International, Inc',
  'Merisant Company',
  'Acadian Seaplants Limited',
  'The Quaker Oats, Co',
  'Arizona Beverage Co',
  'McKee Baking, Co',
  'Mead Johnson',
  'McNeil Nutritionals, LLC',
  'Rockstar, Inc',
  'Dennys',
  'Hain Celestial Group, Inc',
  'Attune Foods, Inc',
  'McNeil Nutritionals/McNeil_PPC, Inc',
  'Ovaltine',
  'Wendys International, Inc',
  'Salada',
  'Archway Cookies</option>'
];
